/*
 * This source file was generated by the Gradle 'init' task
 */
package l1c;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  /*  @Test void appHasAGreeting() {
        RunYBase classUnderTest = new RunYBase();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }*/
}
