/*
 * This source file was generated by the Gradle 'init' task
 */
package l1c;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;

import javax.swing.Timer;
import javax.swing.AbstractAction;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JPopupMenu;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.ListCellRenderer;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.text.JTextComponent;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

public class RunYBase {

    // #region ========== НАСТРОЙКИ ==========
    private static final boolean SHOW_DEBUG_PANEL = false;
    private static final boolean SHOW_RUN_MESSAGE = true;
    private static final int MAX_HISTORY_SIZE = 20;
    private static final String HISTORY_DIR = ".1c_launcher";
    private static final String HISTORY_FILE = "history.xml";
    // #endregion =================================

    // @formatter:off
   // #region ========== ЦВЕТА 1С (белый фон + приглушённые жёлтые акценты) ==========
    private static final Color COLOR_BG = new Color(255, 255, 255);        // Белый фон
    private static final Color COLOR_BUTTON_BG = new Color(230, 200, 120); // Приглушённый жёлто-песочный
    private static final Color COLOR_BUTTON_FG = Color.BLACK;              // Чёрный текст на кнопках
    private static final Color COLOR_ACCENT = new Color(200, 160, 70);     // Приглушённый для рамок
    private static final Color COLOR_TEXT_FG = new Color(0, 0, 0);         // Чёрный текст
    private static final Color COLOR_INPUT_BG = new Color(255, 255, 255);  // Белый фон полей ввода
    private static final Color COLOR_OUTPUT_BG = new Color(250, 250, 250); // Светло-серый фон для вывода
    private static final Color COLOR_PANEL_BG = new Color(255, 255, 255);  // Белый фон панелей
    // #endregion =================================
    // @formatter:on

    private static HintComboBox addressComboBox;
    private static JTextArea outputArea86;
    private static JTextArea outputArea;
    private static JRadioButton designerRadio;
    private static JRadioButton thinRadio;
    private static JRadioButton thickOrdinaryRadio;
    private static JRadioButton thickManagedRadio;
    private static ButtonGroup modeGroup;
    private static JTextArea debugArea;
    private static DefaultComboBoxModel<String> historyModel;
    
    // Хранилище для учётных данных (адрес -> credentials)
    private static java.util.Map<String, UserCredentials> credentialsMap = new java.util.HashMap<>();

        // Вспомогательный метод для создания объёмной кнопки
    private static JButton createButton(String text) {
        JButton button = new JButton(text);
        button.setBackground(COLOR_BUTTON_BG);
        button.setForeground(COLOR_BUTTON_FG);
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createRaisedBevelBorder(),
                BorderFactory.createEmptyBorder(2, 10, 2, 10)));
        button.setFont(new Font("Segoe UI", Font.BOLD, 11));

        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createLoweredBevelBorder(),
                        BorderFactory.createEmptyBorder(2, 10, 2, 10)));
            }

            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createRaisedBevelBorder(),
                        BorderFactory.createEmptyBorder(2, 10, 2, 10)));
            }
        });
        return button;
    }

    // Вспомогательный метод для создания плоской кнопки
    private static JButton createFlatButton(String text) {
        JButton button = new JButton(text);
        button.setBackground(COLOR_INPUT_BG);
        button.setForeground(COLOR_TEXT_FG);
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        button.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        button.setContentAreaFilled(true);
        button.setOpaque(false);
        return button;
    }

    public static void main(String[] args) {
        loadCredentials(); // Загружаем сохранённые учётные данные
        loadHistoryFromXml();

        JFrame frame = new JFrame(
                "Построитель команды запуска 1С - Примеры: File=\"C:\\1C\\Base\";  или  Srvr=\"127.0.0.1\";Ref=\"Base\";");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(1050, SHOW_DEBUG_PANEL ? 700 : 500);
        frame.getContentPane().setBackground(COLOR_BG);
        frame.setLayout(new FlowLayout());

        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panel.setBackground(COLOR_BG);

        // #region ОбластьАдресаБД
        JPanel inputPanel = new JPanel(new BorderLayout(5, 5));
        inputPanel.setBackground(COLOR_BG);

        JLabel addressLabel = new JLabel("Адрес БД:");
        addressLabel.setForeground(COLOR_TEXT_FG);
        addressLabel.setFont(new Font("Segoe UI", Font.BOLD, 12));

        JPanel labelPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        labelPanel.setBackground(COLOR_BG);
        labelPanel.add(addressLabel);
        inputPanel.add(labelPanel, BorderLayout.WEST);

        historyModel = new DefaultComboBoxModel<>();
        for (String addr : getHistoryList()) {
            historyModel.addElement(addr);
        }
        addressComboBox = new HintComboBox(historyModel,
                "для файловой 'File=\"C:\\1C\\Base\";' для серверной 'Srvr=\"127.0.0.1\";Ref=\"Base\";'");
        addressComboBox.setBackground(COLOR_INPUT_BG);
        addressComboBox.setToolTipText("Например File=\"C:\\1C\\Base\"  или  Srvr=\"127.0.0.1\";Ref=\"Base\"");

        // Обёртка для ComboBox с кнопкой
        JPanel comboBoxPanel = new JPanel(new BorderLayout(0, 0));
        comboBoxPanel.setBackground(COLOR_INPUT_BG);
        comboBoxPanel.add(addressComboBox, BorderLayout.CENTER);

        JButton selectButton = createFlatButton("…");
        selectButton.setToolTipText("Выбрать из списка зарегистрированных баз");
        selectButton.addActionListener(e -> selectDatabaseFromList());
        selectButton.setPreferredSize(new Dimension(25, 30));
        selectButton.setMaximumSize(new Dimension(25, 30));
        selectButton.setMinimumSize(new Dimension(25, 30));
        comboBoxPanel.add(selectButton, BorderLayout.EAST);

        inputPanel.add(comboBoxPanel, BorderLayout.CENTER);

        JPanel rightPanel = new JPanel(new GridLayout(2, 1, 5, 5));
        rightPanel.setBackground(COLOR_BG);

        JPanel topButtonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 5, 0));
        topButtonPanel.setBackground(COLOR_BG);

        JButton userButton = createButton("Пользователь");
        userButton.addActionListener(e -> showUserCredentialsDialog());

        topButtonPanel.add(userButton);

        JButton button = createButton("Сформировать");
        button.addActionListener(e -> handleButtonClick());

        rightPanel.add(topButtonPanel);
        rightPanel.add(button);
        inputPanel.add(rightPanel, BorderLayout.EAST);

        panel.add(inputPanel);
        // #endregion

        // #region Режим запуска
        JPanel modePanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        modePanel.setBackground(COLOR_PANEL_BG);

        JLabel modeLabel = new JLabel("Режим запуска:");
        modeLabel.setForeground(COLOR_TEXT_FG);
        modeLabel.setFont(new Font("Segoe UI", Font.BOLD, 12));
        modePanel.add(modeLabel);

        designerRadio = new JRadioButton("Конфигуратор", true);
        thinRadio = new JRadioButton("Тонкий клиент");
        thickOrdinaryRadio = new JRadioButton("Толстый клиент (Обычное приложение)");
        thickManagedRadio = new JRadioButton("Толстый клиент (Управляемое приложение)");

        JRadioButton[] radios = { designerRadio, thinRadio, thickOrdinaryRadio, thickManagedRadio };
        for (JRadioButton rb : radios) {
            rb.setBackground(COLOR_PANEL_BG);
            rb.setForeground(COLOR_TEXT_FG);
            rb.setFont(new Font("Segoe UI", Font.PLAIN, 11));
        }

        modeGroup = new ButtonGroup();
        modeGroup.add(designerRadio);
        modeGroup.add(thinRadio);
        modeGroup.add(thickOrdinaryRadio);
        modeGroup.add(thickManagedRadio);

        modePanel.add(designerRadio);
        modePanel.add(Box.createRigidArea(new Dimension(15, 0)));
        modePanel.add(thinRadio);
        modePanel.add(Box.createRigidArea(new Dimension(15, 0)));
        modePanel.add(thickOrdinaryRadio);
        modePanel.add(Box.createRigidArea(new Dimension(15, 0)));
        modePanel.add(thickManagedRadio);

        panel.add(modePanel);
        panel.add(Box.createRigidArea(new Dimension(0, 15)));
        // #endregion

        // Заголовки для вывода
        JLabel label86 = new JLabel("Команда для 32-битной платформы (x86):");
        JPanel header86Panel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        header86Panel.setBackground(COLOR_BG);
        header86Panel.add(label86);
        panel.add(header86Panel);

        // Блок для x86
        JPanel p86 = new JPanel(new BorderLayout(5, 0));
        p86.setBackground(COLOR_BG);
        outputArea86 = new JTextArea(4, 85);
        outputArea86.setFont(new Font("Consolas", Font.PLAIN, 11));
        p86.add(new JScrollPane(outputArea86), BorderLayout.CENTER);

        JPanel buttonPanel86 = new JPanel(new GridLayout(2, 1, 5, 5));
        buttonPanel86.setBackground(COLOR_BG);

        JButton copy86 = createButton("Copy");
        copy86.addActionListener(e -> copyToClipboard(outputArea86.getText()));

        JButton run86 = createButton("Run");
        run86.addActionListener(e -> runCommand(outputArea86.getText(), "x86"));

        buttonPanel86.add(copy86);
        buttonPanel86.add(run86);
        p86.add(buttonPanel86, BorderLayout.EAST);
        panel.add(p86);

        panel.add(Box.createRigidArea(new Dimension(0, 10)));

        // Заголовки для x64
        JLabel label64 = new JLabel("Команда для 64-битной платформы (x64):");
        JPanel header64Panel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        header64Panel.setBackground(COLOR_BG);
        header64Panel.add(label64);
        panel.add(header64Panel);

        // Блок для x64
        JPanel p64 = new JPanel(new BorderLayout(5, 0));
        p64.setBackground(COLOR_BG);
        outputArea = new JTextArea(4, 85);
        outputArea.setFont(new Font("Consolas", Font.PLAIN, 11));
        p64.add(new JScrollPane(outputArea), BorderLayout.CENTER);

        JPanel buttonPanel64 = new JPanel(new GridLayout(2, 1, 5, 5));
        buttonPanel64.setBackground(COLOR_BG);

        JButton copy64 = createButton("Copy");
        copy64.addActionListener(e -> copyToClipboard(outputArea.getText()));

        JButton run64 = createButton("Run");
        run64.addActionListener(e -> runCommand(outputArea.getText(), "x64"));

        buttonPanel64.add(copy64);
        buttonPanel64.add(run64);
        p64.add(buttonPanel64, BorderLayout.EAST);
        panel.add(p64);

        if (SHOW_DEBUG_PANEL) {
            panel.add(Box.createRigidArea(new Dimension(0, 10)));
            JLabel debugLabel = new JLabel("Отладка (вывод команды и ошибок):");
            debugLabel.setForeground(COLOR_TEXT_FG);
            debugLabel.setFont(new Font("Segoe UI", Font.BOLD, 11));
            panel.add(debugLabel);

            debugArea = new JTextArea(8, 85);
            debugArea.setFont(new Font("Consolas", Font.PLAIN, 11));
            debugArea.setBackground(COLOR_OUTPUT_BG);
            debugArea.setForeground(COLOR_TEXT_FG);
            debugArea.setBorder(new LineBorder(COLOR_ACCENT, 1));
            JScrollPane debugScroll = new JScrollPane(debugArea);
            panel.add(debugScroll);
        } else {
            debugArea = new JTextArea();
        }

        frame.add(panel);
        frame.setLocationRelativeTo(null);

        frame.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(KeyStroke.getKeyStroke("ESCAPE"), "closeWindow");
        frame.getRootPane().getActionMap().put("closeWindow", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                saveCredentials();
                saveHistoryToXml();
                System.exit(0);
            }
        });

        frame.setVisible(true);

        Component editorComp = addressComboBox.getEditor().getEditorComponent();
        if (editorComp instanceof JTextComponent) {
            addContextMenu((JTextComponent) editorComp);
        }
        addContextMenu(outputArea);
        addContextMenu(outputArea86);
        if (debugArea != null)
            addContextMenu(debugArea);

        autoPasteFromClipboard();

        addressComboBox.requestFocus();
    }

    // -----------------------------------------------------------------
    // Учётные данные пользователей
    // -----------------------------------------------------------------
    
    private static Path getCredentialsPath() {
        String userHome = System.getProperty("user.home");
        Path dir = Paths.get(userHome, HISTORY_DIR);
        try {
            Files.createDirectories(dir);
        } catch (IOException e) {
            System.err.println("Не удалось создать директорию для истории: " + dir);
        }
        return dir.resolve("credentials.xml");
    }
    
    private static void loadCredentials() {
        Path path = getCredentialsPath();
        if (!Files.exists(path)) {
            return;
        }
        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document doc = builder.parse(path.toFile());
            
            NodeList credNodes = doc.getElementsByTagName("credential");
            for (int i = 0; i < credNodes.getLength(); i++) {
                Element elem = (Element) credNodes.item(i);
                String address = getTagValue("address", elem);
                String username = getTagValue("username", elem);
                String encryptedPassword = getTagValue("password", elem);
                
                if (address != null && username != null && !address.isEmpty()) {
                    String password = encryptedPassword != null ? decrypt(encryptedPassword) : "";
                    credentialsMap.put(address, new UserCredentials(username, password));
                }
            }
        } catch (Exception e) {
            System.err.println("Ошибка загрузки учётных данных: " + e.getMessage());
        }
    }
    
    private static void saveCredentials() {
        Path path = getCredentialsPath();
        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document doc = builder.newDocument();
            
            Element root = doc.createElement("credentials");
            doc.appendChild(root);
            
            for (java.util.Map.Entry<String, UserCredentials> entry : credentialsMap.entrySet()) {
                Element credElem = doc.createElement("credential");
                
                Element addrElem = doc.createElement("address");
                addrElem.setTextContent(entry.getKey());
                credElem.appendChild(addrElem);
                
                Element userElem = doc.createElement("username");
                userElem.setTextContent(entry.getValue().getUsername());
                credElem.appendChild(userElem);
                
                Element passElem = doc.createElement("password");
                passElem.setTextContent(encrypt(entry.getValue().getPassword()));
                credElem.appendChild(passElem);
                
                root.appendChild(credElem);
            }
            
            TransformerFactory transformerFactory = TransformerFactory.newInstance();
            Transformer transformer = transformerFactory.newTransformer();
            transformer.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
            transformer.setOutputProperty(OutputKeys.INDENT, "yes");
            transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "2");
            DOMSource source = new DOMSource(doc);
            StreamResult result = new StreamResult(path.toFile());
            transformer.transform(source, result);
        } catch (Exception e) {
            System.err.println("Ошибка сохранения учётных данных: " + e.getMessage());
        }
    }
    
    // Простое XOR-шифрование (для демонстрации, в реальном проекте используйте более стойкое)
    private static final String KEY = "1C_Launcher_2026_Secret_Key";
    
    private static String encrypt(String input) {
        if (input == null || input.isEmpty()) return "";
        byte[] inputBytes = input.getBytes(StandardCharsets.UTF_8);
        byte[] keyBytes = KEY.getBytes(StandardCharsets.UTF_8);
        byte[] result = new byte[inputBytes.length];
        for (int i = 0; i < inputBytes.length; i++) {
            result[i] = (byte) (inputBytes[i] ^ keyBytes[i % keyBytes.length]);
        }
        return Base64.getEncoder().encodeToString(result);
    }
    
    private static String decrypt(String input) {
        if (input == null || input.isEmpty()) return "";
        byte[] inputBytes = Base64.getDecoder().decode(input);
        byte[] keyBytes = KEY.getBytes(StandardCharsets.UTF_8);
        byte[] result = new byte[inputBytes.length];
        for (int i = 0; i < inputBytes.length; i++) {
            result[i] = (byte) (inputBytes[i] ^ keyBytes[i % keyBytes.length]);
        }
        return new String(result, StandardCharsets.UTF_8);
    }
    
    private static void showUserCredentialsDialog() {
        String address = getCurrentAddress();
        if (address.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Сначала введите адрес базы данных!", 
                    "Предупреждение", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        UserCredentials existing = credentialsMap.get(address);
        String currentUsername = existing != null ? existing.getUsername() : "";
        String currentPassword = existing != null ? existing.getPassword() : "";
        
        JTextField usernameField = new JTextField(currentUsername, 20);
        JPasswordField passwordField = new JPasswordField(currentPassword, 20);
        
        JPanel panel = new JPanel(new GridLayout(3, 2, 10, 10));
        panel.add(new JLabel("Имя пользователя:"));
        panel.add(usernameField);
        panel.add(new JLabel("Пароль:"));
        panel.add(passwordField);
        
        int result = JOptionPane.showConfirmDialog(null, panel, 
                "Учётные данные для базы\n" + address, 
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        if (result == JOptionPane.OK_OPTION) {
            String username = usernameField.getText().trim();
            String password = new String(passwordField.getPassword());
            
            if (!username.isEmpty()) {
                credentialsMap.put(address, new UserCredentials(username, password));
                saveCredentials();
                JOptionPane.showMessageDialog(null, "Учётные данные сохранены для адреса:\n" + address);
            } else if (existing != null) {
                // Если поле имени пустое — удаляем запись
                credentialsMap.remove(address);
                saveCredentials();
                JOptionPane.showMessageDialog(null, "Учётные данные удалены для адреса:\n" + address);
            }
        }
    }
    
    private static void askAndRunWithCredentials(String address, String baseCommand) {
        UserCredentials cred = credentialsMap.get(address);
        if (cred != null && !cred.getUsername().isEmpty()) {
            int answer = JOptionPane.showConfirmDialog(null,
                    "Запустить от имени пользователя:\n" + cred.getUsername() + 
                    (cred.getPassword().isEmpty() ? "\n(без пароля)" : ""),
                    "Запуск с учётными данными",
                    JOptionPane.YES_NO_OPTION);
            
            if (answer == JOptionPane.YES_OPTION) {
                String cmd = baseCommand;
                cmd += " /UserName \"" + cred.getUsername() + "\"";
                if (!cred.getPassword().isEmpty()) {
                    cmd += " /Password \"" + cred.getPassword() + "\"";
                }
                runCommand(cmd, "с учётными данными");
            } else {
                runCommand(baseCommand, "без учётных данных");
            }
        } else {
            runCommand(baseCommand, "");
        }
    }

    // -----------------------------------------------------------------
    // Работа с историей в XML (домашняя папка)
    // -----------------------------------------------------------------
    private static Path getHistoryPath() {
        String userHome = System.getProperty("user.home");
        Path dir = Paths.get(userHome, HISTORY_DIR);
        try {
            Files.createDirectories(dir);
        } catch (IOException e) {
            System.err.println("Не удалось создать директорию для истории: " + dir);
        }
        return dir.resolve(HISTORY_FILE);
    }

    private static List<String> getHistoryList() {
        List<String> list = new ArrayList<>();
        Path path = getHistoryPath();
        if (!Files.exists(path)) {
            createDefaultHistoryFile(path);
            return list;
        }
        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document doc = builder.parse(path.toFile());
            NodeList addrNodes = doc.getElementsByTagName("address");
            for (int i = 0; i < addrNodes.getLength(); i++) {
                String addr = addrNodes.item(i).getTextContent();
                if (addr != null && !addr.trim().isEmpty() && !list.contains(addr.trim())) {
                    list.add(addr.trim());
                }
            }
        } catch (ParserConfigurationException | SAXException | IOException e) {
            System.err.println("Ошибка загрузки истории из XML. Будет создан новый файл.");
            e.printStackTrace();
            createDefaultHistoryFile(path);
        }
        return list;
    }

    private static void loadHistoryFromXml() {
        // данные уже загружены через getHistoryList()
    }

    private static void createDefaultHistoryFile(Path path) {
        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document doc = builder.newDocument();

            Element root = doc.createElement("history");
            doc.appendChild(root);

            root.appendChild(doc.createComment(
                    " Файл истории адресов баз 1С.\n" +
                            " Содержит последние использованные адреса для быстрого выбора.\n" +
                            " Если удалить или очистить этот файл, история будет восстановлена при следующем запуске программы (пустая).\n"
                            +
                            " Рекомендуется не редактировать файл вручную. Если всё же редактируете, сделайте резервную копию.\n"));

            Element addresses = doc.createElement("addresses");
            root.appendChild(addresses);

            TransformerFactory transformerFactory = TransformerFactory.newInstance();
            Transformer transformer = transformerFactory.newTransformer();
            transformer.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
            transformer.setOutputProperty(OutputKeys.INDENT, "yes");
            transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "2");
            DOMSource source = new DOMSource(doc);
            StreamResult result = new StreamResult(path.toFile());
            transformer.transform(source, result);
        } catch (Exception e) {
            System.err.println("Не удалось создать файл истории по умолчанию: " + path);
            e.printStackTrace();
        }
    }

    private static void addToHistory(String address) {
        if (address == null || address.isEmpty())
            return;
        historyModel.removeElement(address);
        historyModel.insertElementAt(address, 0);
        while (historyModel.getSize() > MAX_HISTORY_SIZE) {
            historyModel.removeElementAt(historyModel.getSize() - 1);
        }
        addressComboBox.setSelectedItem(address);
        saveHistoryToXml();
    }

    private static void saveHistoryToXml() {
        Path path = getHistoryPath();
        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document doc = builder.newDocument();

            Element root = doc.createElement("history");
            doc.appendChild(root);

            root.appendChild(doc.createComment(
                    " Файл истории адресов баз 1С.\n" +
                            " Содержит последние использованные адреса для быстрого выбора.\n" +
                            " Если удалить или очистить этот файл, история будет восстановлена при следующем запуске программы (пустая).\n"
                            +
                            " Рекомендуется не редактировать файл вручную. Если всё же редактируете, сделайте резервную копию.\n"));

            Element addresses = doc.createElement("addresses");
            root.appendChild(addresses);

            for (int i = 0; i < historyModel.getSize(); i++) {
                String addr = historyModel.getElementAt(i);
                Element addrElem = doc.createElement("address");
                addrElem.setTextContent(addr);
                addresses.appendChild(addrElem);
            }

            TransformerFactory transformerFactory = TransformerFactory.newInstance();
            Transformer transformer = transformerFactory.newTransformer();
            transformer.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
            transformer.setOutputProperty(OutputKeys.INDENT, "yes");
            transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "2");
            DOMSource source = new DOMSource(doc);
            StreamResult result = new StreamResult(path.toFile());
            transformer.transform(source, result);
        } catch (Exception e) {
            System.err.println("Ошибка сохранения истории в XML: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private static boolean isDatabaseAddress(String text) {
        if (text == null || text.isEmpty())
            return false;
        String trimmed = text.trim();
        return trimmed.startsWith("File=") || trimmed.startsWith("Srvr=");
    }

    private static void autoPasteFromClipboard() {
        try {
            java.awt.datatransfer.Clipboard clipboard = java.awt.Toolkit.getDefaultToolkit().getSystemClipboard();
            java.awt.datatransfer.Transferable contents = clipboard.getContents(null);

            if (contents != null && contents.isDataFlavorSupported(java.awt.datatransfer.DataFlavor.stringFlavor)) {
                String text = (String) contents.getTransferData(java.awt.datatransfer.DataFlavor.stringFlavor);
                if (isDatabaseAddress(text)) {
                    ((HintComboBox) addressComboBox).setRealText(text);
                    JOptionPane.showMessageDialog(null,
                            "Обнаружен адрес базы 1С в буфере обмена!\n\nАвтоматически вставлено:\n" + text,
                            "Автовставка из буфера", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }
            addressComboBox.setSelectedItem(null);
            addressComboBox.getEditor().setItem("");
        } catch (Exception e) {
            addressComboBox.setSelectedItem(null);
            addressComboBox.getEditor().setItem("");
        }
    }

    private static String getCurrentAddress() {
        Object sel = addressComboBox.getSelectedItem();
        return sel == null ? "" : sel.toString().trim();
    }

    private static String getCommandPart() {
        if (designerRadio.isSelected())
            return "DESIGNER";
        if (thinRadio.isSelected())
            return "ENTERPRISE /ThinClient";
        if (thickOrdinaryRadio.isSelected())
            return "ENTERPRISE /RunModeOrdinaryApplication";
        return "ENTERPRISE /RunModeManagedApplication";
    }

    private static void handleButtonClick() {
        String text = getCurrentAddress();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Введите адрес базы данных! Например:\n\nФайловая БД: File=\"C:\\1C\\Base\"\nКлиент-сервер: Srvr=\"127.0.0.1\";Ref=\"Base\";",
                    "Предупреждение", JOptionPane.WARNING_MESSAGE);
            return;
        }

        addToHistory(text);

        String commandPart = getCommandPart();
        outputArea86.setText("");
        outputArea.setText("");

        String escaped = text.replace("\"", "\"\"");
        String cmd86 = "\"C:\\Program Files (x86)\\1cv8\\common\\1cestart.exe\" " + commandPart
                + " /IBConnectionString \"" + escaped + "\"";
        String cmd64 = "\"C:\\Program Files\\1cv8\\common\\1cestart.exe\" " + commandPart + " /IBConnectionString \"" + escaped + "\"";
        
        // Проверяем, есть ли учётные данные для этого адреса
        UserCredentials cred = credentialsMap.get(text);
        if (cred != null && !cred.getUsername().isEmpty()) {
            cmd86 += " /N \"" + cred.getUsername() + "\"";
            cmd64 += " /N \"" + cred.getUsername() + "\"";
            if (!cred.getPassword().isEmpty()) {
                cmd86 += " /P \"" + cred.getPassword() + "\"";
                cmd64 += " /P \"" + cred.getPassword() + "\"";
            }
        }
        
        outputArea86.append(cmd86);
        outputArea.append(cmd64);

        if (debugArea != null && SHOW_DEBUG_PANEL)
            debugArea.setText("");
    }

    private static void runCommand(String command, String platform) {
        if (command == null || command.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Нет команды для запуска!", "Ошибка", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (SHOW_DEBUG_PANEL && debugArea != null) {
            debugArea.append("=== Запуск (" + platform + ") ===\nКоманда: " + command + "\n");
        }
        try {
            List<String> args = parseCommand(command);
            ProcessBuilder pb = new ProcessBuilder(args);
            pb.redirectErrorStream(true);
            Process process = pb.start();

            BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
            StringBuilder output = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null)
                output.append(line).append("\n");

            boolean finished = process.waitFor(3, java.util.concurrent.TimeUnit.SECONDS);
            String mode = designerRadio.isSelected() ? "Конфигуратор"
                    : thinRadio.isSelected() ? "Тонкий клиент"
                            : thickOrdinaryRadio.isSelected() ? "Толстый клиент (Обычное)"
                                    : "Толстый клиент (Управляемое)";

            if (finished) {
                int code = process.exitValue();
                if (code == 0) {
                    if (SHOW_RUN_MESSAGE) {
                        showAutoClosingDialog(
                                mode + " успешно запущен!\nБаза: " + getCurrentAddress() + "\nПлатформа: " + platform,
                                "Запуск 1С",
                                JOptionPane.INFORMATION_MESSAGE,
                                5);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Ошибка запуска " + mode + "!\nКод: " + code, "Ошибка",
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                if (SHOW_RUN_MESSAGE) {
                    showAutoClosingDialog(
                            mode + " запущен (фоновый процесс).\nБаза: " + getCurrentAddress(),
                            "Запуск 1С",
                            JOptionPane.INFORMATION_MESSAGE,
                            5);
                }
            }
            if (SHOW_DEBUG_PANEL && debugArea != null)
                debugArea.append("=== Конец запуска ===\n\n");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ошибка запуска: " + e.getMessage(), "Ошибка",
                    JOptionPane.ERROR_MESSAGE);
            if (SHOW_DEBUG_PANEL && debugArea != null)
                debugArea.append("Исключение: " + e + "\n");
        }
    }

    // Вспомогательный метод для автоматического закрытия диалога
    private static void showAutoClosingDialog(String message, String title, int messageType, int delaySeconds) {
        final JDialog dialog = new JDialog();
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.setModal(false);

        JOptionPane optionPane = new JOptionPane(message, messageType);
        dialog.setContentPane(optionPane);
        dialog.pack();
        dialog.setLocationRelativeTo(null);

        Timer timer = new Timer(delaySeconds * 1000, e -> dialog.dispose());
        timer.setRepeats(false);
        timer.start();

        dialog.setVisible(true);
    }

    private static List<String> parseCommand(String command) {
        List<String> args = new ArrayList<>();
        StringBuilder cur = new StringBuilder();
        boolean inQuotes = false;
        for (int i = 0; i < command.length(); i++) {
            char c = command.charAt(i);
            if (c == '"') {
                inQuotes = !inQuotes;
                continue;
            }
            if (c == ' ' && !inQuotes) {
                if (cur.length() > 0) {
                    args.add(cur.toString());
                    cur.setLength(0);
                }
                continue;
            }
            cur.append(c);
        }
        if (cur.length() > 0)
            args.add(cur.toString());
        for (int i = 0; i < args.size(); i++) {
            String a = args.get(i);
            if (a.startsWith("\"") && a.endsWith("\"") && a.length() > 1)
                args.set(i, a.substring(1, a.length() - 1));
        }
        return args;
    }

    private static void addContextMenu(JTextComponent comp) {
        JPopupMenu menu = new JPopupMenu();
        JMenuItem paste = new JMenuItem("Вставить");
        paste.addActionListener(e -> comp.paste());
        JMenuItem cut = new JMenuItem("Вырезать");
        cut.addActionListener(e -> comp.cut());
        JMenuItem copy = new JMenuItem("Копировать");
        copy.addActionListener(e -> comp.copy());
        JMenuItem selectAll = new JMenuItem("Выделить всё");
        selectAll.addActionListener(e -> comp.selectAll());
        menu.add(paste);
        menu.add(cut);
        menu.add(copy);
        menu.addSeparator();
        menu.add(selectAll);
        comp.setComponentPopupMenu(menu);
    }

    private static void copyToClipboard(String text) {
        if (text == null || text.isEmpty())
            return;
        java.awt.datatransfer.StringSelection sel = new java.awt.datatransfer.StringSelection(text);
        java.awt.Toolkit.getDefaultToolkit().getSystemClipboard().setContents(sel, null);
        JOptionPane.showMessageDialog(null, "Команда скопирована в буфер обмена!", "Успешно",
                JOptionPane.INFORMATION_MESSAGE);
    }

    // Получение отсортированного списка баз из файла
    private static List<BaseEntry> loadAndSortDatabases()
            throws IOException, ParserConfigurationException, SAXException, Exception {
        String userHome = System.getProperty("user.home");
        Path ibasesPath = Paths.get(userHome, "AppData", "Roaming", "1C", "1CEStart", "ibases.v8i");

        if (!Files.exists(ibasesPath)) {
            JOptionPane.showMessageDialog(null,
                    "Файл списка баз не найден:\n" + ibasesPath.toString(),
                    "Ошибка", JOptionPane.ERROR_MESSAGE);
            return new ArrayList<>();
        }

        List<BaseEntry> baseEntries = new ArrayList<>();

        String content = new String(Files.readAllBytes(ibasesPath), StandardCharsets.UTF_8);

        if (content.trim().startsWith("<?xml") || content.contains("<infobase>")) {
            parseXmlFormatWithOrder(ibasesPath, baseEntries);
        } else {
            parseIniFormatWithOrder(ibasesPath, baseEntries);
        }

        baseEntries.sort((a, b) -> a.name.compareToIgnoreCase(b.name));

        return baseEntries;
    }

    // Показ окна выбора базы из списка баз
    private static void selectDatabaseFromList() {
        try {
            List<BaseEntry> baseEntries = loadAndSortDatabases();

            if (baseEntries.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Нет зарегистрированных баз 1С",
                        "Список баз", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            JList<BaseEntry> list = new JList<>(baseEntries.toArray(new BaseEntry[0]));
            list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            list.setCellRenderer(new BaseEntryListRenderer());

            JScrollPane scrollPane = new JScrollPane(list);
            scrollPane.setPreferredSize(new Dimension(600, 400));
            scrollPane.setBorder(BorderFactory.createTitledBorder("Зарегистрированные базы 1С"));

            JPanel panel = new JPanel(new BorderLayout(10, 10));
            panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

            JDialog dialog = new JDialog();
            dialog.setTitle("Выбор базы 1С");
            dialog.setModal(true);
            dialog.setResizable(true);
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

            dialog.getRootPane().registerKeyboardAction(e -> dialog.dispose(),
                    KeyStroke.getKeyStroke("ESCAPE"),
                    JComponent.WHEN_IN_FOCUSED_WINDOW);

            JButton okButton = new JButton("OK");
            okButton.addActionListener(e -> {
                BaseEntry selected = list.getSelectedValue();
                if (selected != null) {
                    ((HintComboBox) addressComboBox).setRealText(selected.connect);
                }
                dialog.dispose();
            });

            JButton cancelButton = new JButton("Отмена");
            cancelButton.addActionListener(e -> dialog.dispose());

            list.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (evt.getClickCount() == 2) {
                        BaseEntry selected = list.getSelectedValue();
                        if (selected != null) {
                            ((HintComboBox) addressComboBox).setRealText(selected.connect);
                            dialog.dispose();
                        }
                    }
                }
            });

            JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
            buttonPanel.add(okButton);
            buttonPanel.add(cancelButton);

            panel.add(scrollPane, BorderLayout.CENTER);
            panel.add(buttonPanel, BorderLayout.SOUTH);

            dialog.add(panel);
            dialog.pack();
            dialog.setMinimumSize(new Dimension(650, 450));
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Ошибка при чтении списка баз:\n" + e.getMessage(),
                    "Ошибка", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private static void parseIniFormatWithOrder(Path path, List<BaseEntry> entries) throws IOException {
        List<String> lines = Files.readAllLines(path, StandardCharsets.UTF_8);
        String currentName = null;
        String currentConnect = null;
        double currentOrder = Double.MAX_VALUE;

        for (String line : lines) {
            line = line.trim();
            if (line.isEmpty())
                continue;

            if (line.startsWith("[") && line.endsWith("]")) {
                if (currentName != null && currentConnect != null) {
                    entries.add(new BaseEntry(currentName, currentConnect, currentOrder));
                }
                currentName = line.substring(1, line.length() - 1);
                currentConnect = null;
                currentOrder = Double.MAX_VALUE;
            } else if (line.startsWith("Connect=") && currentName != null) {
                currentConnect = line.substring(8);
            } else if (line.startsWith("OrderInList=") && currentName != null) {
                try {
                    currentOrder = Double.parseDouble(line.substring(12));
                } catch (NumberFormatException e) {
                    currentOrder = Double.MAX_VALUE;
                }
            }
        }

        if (currentName != null && currentConnect != null) {
            entries.add(new BaseEntry(currentName, currentConnect, currentOrder));
        }
    }

    private static void parseXmlFormatWithOrder(Path path, List<BaseEntry> entries) throws Exception {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        DocumentBuilder builder = factory.newDocumentBuilder();
        Document doc = builder.parse(path.toFile());

        NodeList infos = doc.getElementsByTagName("infobase");
        for (int i = 0; i < infos.getLength(); i++) {
            Element info = (Element) infos.item(i);
            String name = getTagValue("name", info);
            String connect = getTagValue("connect", info);
            double order = Double.MAX_VALUE;

            NodeList orderNodes = info.getElementsByTagName("orderInList");
            if (orderNodes.getLength() > 0) {
                try {
                    order = Double.parseDouble(orderNodes.item(0).getTextContent());
                } catch (NumberFormatException e) {
                    order = Double.MAX_VALUE;
                }
            }

            if (name != null && !name.isEmpty() && connect != null && !connect.isEmpty()) {
                entries.add(new BaseEntry(name, connect, order));
            }
        }
    }

    private static String getTagValue(String tag, Element element) {
        NodeList list = element.getElementsByTagName(tag);
        if (list.getLength() == 0)
            return null;
        return list.item(0).getTextContent();
    }

}

// ========== ВСПОМОГАТЕЛЬНЫЕ КЛАССЫ ==========

class HintComboBox extends JComboBox<String> {
    private String hint;

    public HintComboBox(DefaultComboBoxModel<String> history, String hint) {
        super(history);
        this.hint = hint;
        setEditable(true);

        JTextComponent editor = (JTextComponent) getEditor().getEditorComponent();
        editor.setForeground(Color.GRAY);
        editor.setText(hint);

        editor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent e) {
                if (editor.getText().equals(hint)) {
                    editor.setText("");
                    editor.setForeground(Color.BLACK);
                }
            }

            public void focusLost(java.awt.event.FocusEvent e) {
                if (editor.getText().isEmpty()) {
                    editor.setForeground(Color.GRAY);
                    editor.setText(hint);
                }
            }
        });
    }

    public void setRealText(String text) {
        JTextComponent editor = (JTextComponent) getEditor().getEditorComponent();
        editor.setForeground(Color.BLACK);
        editor.setText(text);
        setSelectedItem(text);
    }
}

class BaseEntry {
    String name;
    String connect;
    double order;

    BaseEntry(String name, String connect, double order) {
        this.name = name;
        this.connect = connect;
        this.order = order;
    }
}

class BaseEntryListRenderer extends JPanel implements ListCellRenderer<BaseEntry> {
    private JLabel nameLabel;
    private JLabel connectLabel;

    public BaseEntryListRenderer() {
        setLayout(new BorderLayout(5, 2));
        setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

        nameLabel = new JLabel();
        nameLabel.setFont(new Font("Segoe UI", Font.BOLD, 12));

        connectLabel = new JLabel();
        connectLabel.setFont(new Font("Segoe UI", Font.ITALIC, 10));
        connectLabel.setForeground(Color.BLACK);

        add(nameLabel, BorderLayout.NORTH);
        add(connectLabel, BorderLayout.CENTER);
    }

    @Override
    public Component getListCellRendererComponent(JList<? extends BaseEntry> list,
            BaseEntry value, int index, boolean isSelected, boolean cellHasFocus) {

        nameLabel.setText(value.name);
        connectLabel.setText(value.connect);

        connectLabel.setBorder(BorderFactory.createEmptyBorder(0, 20, 0, 0));

        if (isSelected) {
            setBackground(list.getSelectionBackground());
            setForeground(list.getSelectionForeground());
            nameLabel.setForeground(list.getSelectionForeground());
            connectLabel.setForeground(list.getSelectionForeground());
        } else {
            setBackground(list.getBackground());
            setForeground(list.getForeground());
            nameLabel.setForeground(Color.BLACK);
            connectLabel.setForeground(Color.BLACK);
        }
        setOpaque(true);

        return this;
    }
}

class UserCredentials {
    private String username;
    private String password;
    
    public UserCredentials(String username, String password) {
        this.username = username;
        this.password = password;
    }
    
    public String getUsername() { return username; }
    public String getPassword() { return password; }
}